require 'dotenv'
Dotenv.load

default_platform(:android)

platform :android do
  desc "Lane For Android Firebase Distribution"
  lane :firebase_distribution do
    sh "flutter build apk --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:620508569570:android:7314a2a39e5a8e809ce3bb",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "salafydawah2020@gmail.com",
        release_notes: "First Firebase Distribution by Fastlane",
        upload_timeout: 18000
    )
  end
end
